#!/usr/bin/env python3
'''An API/ Flask project that uses keywords to search for news articles'''

import requests
from flask import Flask, request, render_template

app = Flask(__name__)

# Replace 'YOUR_API_KEY' with your actual News API key
API_KEY = 'acc84431af324dcd9a5a04f090159cc4'       
BASE_URL = 'https://newsapi.org/v2/everything'

@app.route("/", methods=["GET", "POST"])            # initial search page
def main():
    return render_template("index.html")

@app.route("/search", methods=["GET", "POST"])     # search page that loads after typing in keywords
def search_news():
    keyword = request.form.get("keyword")
    params = {                              # Dictionary to allow more than 2 arguements in request funcitons
        "apiKey": API_KEY,
        "q": keyword,
        "pageSize": 10                      # Only grab the first 10 items
    }

    response = requests.get(BASE_URL, params=params)

    if response.status_code == 200:         # Check to make sure an error wasn't received from the websites.
        data = response.json()
        articles = data.get("articles")     # Get the names of the articles returned from the search.

        if articles is None:                                              # Error message if nothing can be returned from search
            message = f"No news articles found for '{keyword}'."   
            return render_template("index.html", message=message, articles=None)

        return render_template("index.html", articles=articles)

    return render_template("index.html", articles=None, message="Error: Unable to fetch news data.")

if __name__ == "__main__":
#    app.run(debug=True)
    app.run(host="0.0.0.0", port=2224, debug=True) # Runs the program on 'aux1' with debuging enabled.