#!/usr/bin/env python3
'''An API/ Flask project that uses keywords to search for news articles'''

import requests

# Replace 'YOUR_API_KEY' with your actual News API key
API_KEY = 'acc84431af324dcd9a5a04f090159cc4'
BASE_URL = 'https://newsapi.org/v2/everything'

def main():
    keyword = input("Enter a keyword to search for news articles: ")
    params = {                                       # Dictionary to allow more than 2 arguements in request funcitons
        'apiKey': API_KEY,
        'q': keyword,
        'pageSize': 10
    }

    response = requests.get(BASE_URL, params=params)

    if response.status_code == 200:       # Output articles or display error
        data = response.json()
        articles = data['articles']
        print(f"Found {len(articles)} articles related to '{keyword}':")
    else:
        print(f"Error: {response.status_code} - Unable to fetch news data.")


    for i, article in enumerate(articles):           # print numbered list with articles
        print(f"{i + 1}. {article['title']}")

    while True:                                       # Allow the user to choose an article to display and loop if the user enters an invalid number.
        choice = int(input("Enter the number of the article you want to read (0 to exit): "))
        if 0 <= choice <= len(articles):
            chosen_article = articles[choice - 1]
            print(f"Title: {chosen_article['title']}")
            print(f"Description: {chosen_article['description']}")
            print(f"URL: {chosen_article['url']}")
            break
        elif choice == 0:
            print('Goodbye!')
            break
        else:
            print("Invalid choice. Please enter a valid number.")
    
if __name__ == "__main__":
    main()