#!/usr/bin/env python3

import pandas 

def main():

    ciscocsv = pandas.read_csv("ciscodata.csv")

    ciscojson = pandas.read_json("ciscodata2.json")

    ciscodata = pandas.concat([ciscocsv, ciscojson], ignore_index=True, sort=True)
    
    x = ciscodata.to_dict(orient='records')
    
    print(x)

if __name__ == "__main__":
    main()
